// React/src/App.tsx
import { useCallback, useState } from 'react';
import Chat, { type ChatTypes } from 'devextreme-react/chat';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';

type User = ChatTypes.User;
type Message = ChatTypes.Message;
type Alert = ChatTypes.Alert;

const firstUser: User = {
  id: '1',
  name: 'User',
};

const secondUser: User = {
  id: '2',
  name: 'Feedback Bot',
  avatarUrl: '/bot.png',
};

const initialMessages: Message[] = [
  {
    timestamp: Date.now(),
    author: secondUser,
    text: 'Hello! We\'d love to hear your feedback. Please share your thoughts below!',
  },
];

function App(): JSX.Element {
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [typingUsers, setTypingUsers] = useState<User[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [disabled, setDisabled] = useState<boolean>(false);

  const sendToBackend = useCallback((): void => {
    setTimeout(() => {
      setTypingUsers([]);
      setMessages((prevMessages) => [
        ...prevMessages,
        {
          text: 'Thanks for helping us improve!',
          author: secondUser,
          timestamp: Date.now(),
        },
      ]);
      setAlerts([
        {
          id: 1,
          message: 'Session expired',
        },
      ]);
      setDisabled(true);
    }, 3000);
  }, []);

  const onMessageEntered = useCallback(
    ({ message }: ChatTypes.MessageEnteredEvent): void => {
      setMessages((prevMessages) => [...prevMessages, message]);
      setTypingUsers([secondUser]);
      sendToBackend();
    },
    [sendToBackend],
  );

  return (
    <Chat
      disabled={disabled}
      alerts={alerts}
      width={400}
      height={450}
      user={firstUser}
      onMessageEntered={onMessageEntered}
      items={messages}
      typingUsers={typingUsers}
    />
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { DxChatModule } from 'devextreme-angular/ui/chat';
import type { DxChatTypes } from 'devextreme-angular/ui/chat';

interface MessageEnteredEvent {
  message: DxChatTypes.Message;
}

@Component({
  selector: 'app-root',
  imports: [DxChatModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  firstUser: DxChatTypes.User = {
    id: '1',
    name: 'User',
  };

  secondUser: DxChatTypes.User = {
    id: '2',
    name: 'Feedback Bot',
    avatarUrl: 'assets/bot.png',
  };

  messages: DxChatTypes.Message[] = [
    {
      timestamp: Date.now(),
      author: this.secondUser,
      text: 'Hello! We\'d love to hear your feedback. Please share your thoughts below!',
    },
  ];

  alerts: DxChatTypes.Alert[] = [];

  typingUsers: DxChatTypes.User[] = [];

  disabled = false;

  onMessageEntered({ message }: MessageEnteredEvent): void {
    this.messages = [...this.messages, message];
    this.typingUsers = [this.secondUser];
    this.sendToBackend();
  }

  sendToBackend(): void {
    setTimeout(() => {
      this.typingUsers = [];
      this.messages = [
        ...this.messages,
        {
          text: 'Thanks for helping us improve!',
          author: this.secondUser,
          timestamp: Date.now(),
        },
      ];
      this.alerts = [
        ...this.alerts,
        {
          id: 1,
          message: 'Session expired',
        },
      ];
      this.disabled = true;
    }, 1000);
  }
}

<dx-splitter
  [width]="500"
  [height]="400"
  [separatorSize]="5"
>
  <dxi-item size="285px">
    <dx-form
      id="form"
      [formData]="employee"
      (onFieldDataChanged)="onFieldDataChanged($event)"
    ></dx-form>
  </dxi-item>
  <dxi-item>
    <dx-splitter orientation="vertical" [separatorSize]="5">
      <dxi-item size="80%">
        <div *ngFor="let item of output">{{ item }}</div>
      </dxi-item>
      <dxi-item [collapsible]="true" minSize="40px">
        <dx-button
          text="Clear all entries"
          (onClick)="resetFormAndOutput()"
        ></dx-button>
      </dxi-item>
      <dxi-item
        [collapsed]="true"
        [collapsible]="true"
        text="All rights are reserved © 2024"
        maxSize="30px"
      ></dxi-item>
    </dx-splitter>
  </dxi-item>
</dx-splitter>
